import {Conversation} from '../conversation';

export const conversations: Array<Conversation> = [
  {
    id: '1',
    name: 'David',
    time: '8:21',
    latestMessage: 'Hi there!!',
    latestMessageRead: false,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '2',
    name: 'James',
    time: '8:21',
    latestMessage: 'wow',
    latestMessageRead: true,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '3',
    name: 'Andrew',
    time: '8:21',
    latestMessage: 'I am fine',
    latestMessageRead: false,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '4',
    name: 'Richard',
    time: '8:21',
    latestMessage: 'lol',
    latestMessageRead: true,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '5',
    name: 'Dyno',
    time: '8:21',
    latestMessage: 'Alright',
    latestMessageRead: false,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '6',
    name: 'Julie',
    time: '8:21',
    latestMessage: "Let's go",
    latestMessageRead: false,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '7',
    name: 'Tom',
    time: '8:21',
    latestMessage: 'I see',
    latestMessageRead: true,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '8',
    name: 'Jerry',
    time: '8:21',
    latestMessage: 'OMG',
    latestMessageRead: false,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '9',
    name: 'Grey',
    time: '8:21',
    latestMessage: 'Oh No',
    latestMessageRead: false,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  },
  {
    id: '10',
    name: 'Jill',
    time: '8:21',
    latestMessage: 'Thanks',
    latestMessageRead: true,
    messages: [
      { id: 1, body: 'Hello world', time: '8:21', me: true },
      { id: 2, body: 'How are you?', time: '8:21', me: false },
      { id: 3, body: 'I am fine thanks', time: '8:21', me: true },
      { id: 4, body: 'Glad to hear that', time: '8:21', me: false },
    ],
  }
]
